apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-06-configmap-dep-03

spec:
  selector:
    matchLabels:
      app: lab-06-configmap-dep-03
  template:
    metadata:
      labels:
        app: lab-06-configmap-dep-03
    spec:
      containers:
      - name: lab-06-configmap-dep-03
        image: nginx
        volumeMounts:
          - name: lab-06-volume
            mountPath: /usr/share/nginx/html
      volumes:
      - name: lab-06-volume
        configMap:
          name: lab-06-volume-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: lab-06-configmap-svc-03

spec:
  selector:
    app: lab-06-configmap-dep-03
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080