apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lab-02-rs-01
  labels:
    app: lab-02-rs-01

spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-02-rs-01
  template:
    metadata:
      labels:
        app: lab-02-rs-01
    spec:
      containers:
      - name: lab-02-rs-01
        image: nginx
        ports:
          - containerPort: 80
