apiVersion: batch/v1
kind: Job
metadata:
  name: lab-08-job-01
spec:
  template:
    metadata:
      name: lab-08-job-01
    spec:
      containers:
      - name: counter
        image: busybox
        command:
         - bin/sh
         - -c
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never #could also be Always or OnFailure