apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-07-secret-01
  labels:
    name: lab-07-secret-01
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: lab-07-secret-01
  template:
    metadata:
      labels:
        name: lab-07-secret-01
    spec:
      containers:
        - name: lab-07-secret-01
          image: nginx
          env:
            - name: api_key
              valueFrom:
                secretKeyRef:
                  name: apikey
                  key: api_key
