apiVersion: v1
kind: Service
metadata:
  name: lab-04-svc-04

spec:
  type: NodePort
  selector:
    app: lab-04-svc-04
  ports:
  - port: 8668
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    targetPort: 80
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767), Optional field
    nodePort: 30080

