apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-04-svc-dep-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-04-svc-dep
  template:
    metadata:
      labels:
        app: lab-04-svc-dep
    spec:
      containers:
        - name: lab-04-svc-dep
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab-04-svc-dep-service
spec:
  type: NodePort
  selector:
    app: lab-04-svc-dep
  ports:
    - port: 8668
      targetPort: 80
