apiVersion: v1
kind: Service
metadata:
  name: lab-04-svc-02

spec:
  selector:
    app: lab-04-svc-02
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9377
