apiVersion: v1
kind: Service
metadata:
  name: lab-04-svc-06

spec:
  type: ExternalName
  externalName: my.example.com
  selector:
    app: lab-04-svc-06
  ports:
  - port: 8668
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    targetPort: 80

